#!/bin/bash

if [ -z "$1" ]; then
echo "No CTID provided."
echo "Usage: $0 ctid"
exit 1
fi

if [ ! -d "/vz/root/$1" ]; then
echo "Container does not exist. Halting."
exit 1
fi

status=$(echo $(vzlist | grep "$1") | grep "running")

if [ -z "$status" ]; then
echo "Container not running. Halting."
exit 1
fi

raw=$(vzctl exec $1 "cat /proc/user_beancounters | grep physpages")
physpages=$(echo "$raw" | awk -F" " '{print $2}')
kbused=$(expr $physpages \* 4)
mbused=$(expr $kbused / 1024)

echo $mbused

